{% set name = "alphalens-reloaded" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: fb3a6ab0f6c5fdb95750181a7b9654f0

build:
  number: 0
  skip: true # [py<37 or not x86_64]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - matplotlib>=1.4.0
    - numpy>=1.9.1
    - pandas>=1.0.0
    - scipy>=0.14.0
    - seaborn>=0.6.0
    - statsmodels>=0.6.1
    - IPython>=3.2.3
    - empyrical-reloaded>=0.5.8

test:
  imports:
    - alphalens

about:
  home: https://alphalens.ml4trading.io
  summary: 'Performance analysis of predictive (alpha) stock factors'
  license: Apache 2.0
  license_file: LICENSE
